### ISSUE TITLE
pip install can't find 'requirements.txt'

### ISSUE THREAD

**Issue by johnmrobinson** [cjsheets/mkdocs-rtd-dropdown#9]
Using python 3.5.x from anaconda. I get the following:
```
(mkdocs-environment) BusterBoy:wellzesta-docs jmr$ pip install mkdocs-rtd-dropdown
Collecting mkdocs-rtd-dropdown
  Using cached mkdocs-rtd-dropdown-0.0.9.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/g_/xb36_7gn2zg21qz3_rlt6k9w0000gp/T/pip-build-mviy3t01/mkdocs-rtd-dropdown/setup.py", line 5, in <module>
        with open("requirements.txt") as data:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/g_/xb36_7gn2zg21qz3_rlt6k9w0000gp/T/pip-build-mviy3t01/mkdocs-rtd-dropdown/
```

**Comment by laoshaw** [comment]
I git clone the repo and did: sudo python3 setup.py install

then it worked fine.

**Comment by spinicist** [comment]
Not even a `setup.py install` works for me on Python 3.6 with Anaconda.

**Comment by cjsheets** [comment]
Thanks for the report. It looks like I left `requirements.txt` out of the Manifest. 

I fixed it and pushed out an updated version.
